import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";

const DEFAULT_MANIFEST = { astroRoot: "astro" };

function readManifest(themeRoot) {
  const manifestPath = path.join(themeRoot, "remote-theme.json");
  if (!existsSync(manifestPath)) return DEFAULT_MANIFEST;

  try {
    return { ...DEFAULT_MANIFEST, ...JSON.parse(readFileSync(manifestPath, "utf8")) };
  } catch (error) {
    throw new Error(`Failed to parse ${manifestPath}: ${error.message}`);
  }
}

function replaceSymlink(linkPath, targetPath) {
  mkdirSync(path.dirname(linkPath), { recursive: true });

  if (existsSync(linkPath) || lstatSync(linkPath, { throwIfNoEntry: false })) {
    rmSync(linkPath, { recursive: true, force: true });
  }

  symlinkSync(targetPath, linkPath, "dir");
}

function ensureDeps(themeAstroDir) {
  const nodeModulesPath = path.join(themeAstroDir, "node_modules");
  if (existsSync(nodeModulesPath)) return;

  console.log(`[remote-astro-theme] Installing theme dependencies in ${themeAstroDir}...`);
  const result = spawnSync("npm", ["install"], {
    cwd: themeAstroDir,
    stdio: "inherit",
  });

  if (result.status !== 0) {
    throw new Error(`"npm install" failed in ${themeAstroDir}`);
  }
}

/**
 * Prepares a runnable Astro workspace out of a resolved theme + a content
 * repo's steering config: locates the theme's Astro project, installs its
 * deps if needed, symlinks content/assets into it (see docs.mindovermachine
 * remote-astro-theme spec §2 for why symlinks + preserveSymlinks are
 * required instead of a bare external path), and writes the generated
 * config file the theme's astro.config.mjs/content.config.ts import.
 */
export function prepareWorkspace({ themeRoot, siteConfig, contentRoot, assetsRoot }) {
  const manifest = readManifest(themeRoot);
  const themeAstroDir = path.join(themeRoot, manifest.astroRoot);

  if (!existsSync(themeAstroDir)) {
    throw new Error(
      `Theme's Astro project not found at ${themeAstroDir} (from remote-theme.json's "astroRoot": "${manifest.astroRoot}").`,
    );
  }

  ensureDeps(themeAstroDir);

  const workspaceDir = path.join(themeAstroDir, ".remote-theme");
  const symlinkedContentDir = path.join(workspaceDir, "content");
  replaceSymlink(symlinkedContentDir, contentRoot);

  const symlinkedAssetsDir = path.join(themeAstroDir, "src", "assets", "remote");
  if (existsSync(assetsRoot)) {
    replaceSymlink(symlinkedAssetsDir, assetsRoot);
  }

  const { theme: _theme, ...siteConfigWithoutThemeField } = siteConfig;
  const generatedConfig = {
    ...siteConfigWithoutThemeField,
    contentRoot: "./.remote-theme/content",
  };

  mkdirSync(workspaceDir, { recursive: true });
  const generatedConfigPath = path.join(workspaceDir, "site-config.generated.mjs");
  writeFileSync(
    generatedConfigPath,
    `// Auto-generated by remote-astro-theme. Do not edit; do not commit.\nexport default ${JSON.stringify(generatedConfig, null, 2)};\n`,
  );

  return {
    themeAstroDir,
    env: {
      REMOTE_THEME_SITE_CONFIG: generatedConfigPath,
      // Build alongside the theme (same filesystem as its own node_modules
      // / .astro temp dirs); the caller copies this out to the content
      // repo's real dist/ afterwards, since Astro's internal build step
      // uses fs.rename() internally which fails across filesystems (EXDEV).
      REMOTE_THEME_OUT_DIR: path.join(workspaceDir, "dist"),
    },
  };
}
